protocol: 'https:'
host: 'ik1-441-52502.vs.sakura.ne.jp'
sitetitle: 'bashcms2ブログ'
sitesubtitle: 'Bootstrapは便利。Pandocも便利。'
links:
- text: '開発日誌（ブログ）'
  href: '/?post'
- text: '外部サイト'
  href: './'
  sublinks:
  - text: '旧bashCMS2作者ブログ'
    href: 'http://test.usptomo.com/'
  - text: 'bashCMS2作者ブログ'
    href: 'https://b.ueda.tech/'
sociallinks:
hatena: '@'
pocket: '@'
twitter: 'MooMoo_Farm'
line: '@'
facebook: '@'
